default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: music-event-app_development

test:
  <<: *default
  database: music-event-app_test

production:
  <<: *default
  database: music-event-app_production
  username: music-event-app
  password: <%= ENV['MUSIC-EVENT-APP_DATABASE_PASSWORD'] %>
